#!/bin/sh

prev="$(pwd)"

cd "$DOTFILES_DIR" || exit 1

git pull origin master

if [ -d OMZ ]; then
	if cd OMZ; then
		git pull origin master
	else
		echo "Error: Unable to acces to OMZ directory: $(pwd)/OMZ"
	fi
fi

cd "$prev" || exit 1

unset prev

echo "Is posible that you need to run 'update-env' to set the enviroment variables"

